#!/usr/bin/env bash
set -e

pushd /etc/nixos
# nvim ndo4.nix
# alejandra . &>/dev/null
# git diff -U0 *.nix
echo "NixOS Rebuilding..."
sudo nixos-rebuild switch --flake /etc/nixos#default
# &>nixos-switch.log || (
# cat nixos-switch.log | grep --color error && false)
gen=$(nixos-rebuild list-generations | grep current)
echo "Latest Gen: $gen"
# git commit -am "$gen"
popd
