[profile.dev]
debug = 0
strip = "debuginfo"

# [target.x86_64-unknown-linux-gnu]
# linker = "/home/ndo/.nix-profile/bin/clang"
# rustflags = ["-C", "link-arg=-fuse-ld=/home/ndo/.nix-profile/bin/mold"]
